export const USER_LOGIN = "USER_LOGIN";
export type USER_LOGIN = typeof USER_LOGIN;

export const USER_LOGOUT = "USER_LOGOUT";
export type USER_LOGOUT = typeof USER_LOGOUT;

export const TEAMS_FOUND = "TEAMS_FOUND";
export type TEAMS_FOUND = typeof TEAMS_FOUND;

export const TEAM_SELECTED = "TEAM_SELECTED";
export type TEAM_SELECTED = typeof TEAM_SELECTED;

export const TEAM_CREATED= "TEAM_CREATED";
export type TEAM_CREATED = typeof TEAM_CREATED;

export const TEAM_DELETED= "TEAM_DELETED";
export type TEAM_DELETED = typeof TEAM_DELETED;

export const PRODUCTS_FOUND= "PRODUCTS_FOUND";
export type PRODUCTS_FOUND = typeof PRODUCTS_FOUND;

export const PRODUCT_SELECTED = "PRODUCT_SELECTED";
export type PRODUCT_SELECTED = typeof PRODUCT_SELECTED;

export const PRODUCT_CREATED= "PRODUCT_CREATED";
export type PRODUCT_CREATED = typeof PRODUCT_CREATED;

export const PRODUCT_DELETED= "PRODUCT_DELETED";
export type PRODUCT_DELETED = typeof PRODUCT_DELETED;

export const PACKAGE_SIZES_FOUND= "PACKAGE_SIZES_FOUND";
export type PACKAGE_SIZES_FOUND = typeof PACKAGE_SIZES_FOUND;

export const PACKAGE_SIZE_SELECTED = "PACKAGE_SIZE_SELECTED";
export type PACKAGE_SIZE_SELECTED = typeof PACKAGE_SIZE_SELECTED;

export const PACKAGE_SIZE_CREATED= "PACKAGE_SIZE_CREATED";
export type PACKAGE_SIZE_CREATED = typeof PACKAGE_SIZE_CREATED;

export const PACKAGE_SIZE_DELETED = "PACKAGE_SIZE_DELETED";
export type PACKAGE_SIZE_DELETED = typeof PACKAGE_SIZE_DELETED;

export const SEEDS_FOUND = "SEEDS_FOUND";
export type SEEDS_FOUND = typeof SEEDS_FOUND;

export const SEED_SELECTED = "SEED_SELECTED";
export type SEED_SELECTED = typeof SEED_SELECTED;

export const SEED_CREATED = "SEED_CREATED";
export type SEED_CREATED = typeof SEED_CREATED;

export const SEED_DELETED = "SEED_DELETED";
export type SEED_DELETED = typeof SEED_DELETED;

export const PRODUCTION_LINES_FOUND = "PRODUCTION_LINES_FOUND";
export type PRODUCTION_LINES_FOUND = typeof PRODUCTION_LINES_FOUND;

export const PRODUCTION_LINE_SELECTED = "PRODUCTION_LINE_SELECTED";
export type PRODUCTION_LINE_SELECTED = typeof PRODUCTION_LINE_SELECTED;

export const PRODUCTION_LINE_CREATED = "PRODUCTION_LINE_CREATED";
export type PRODUCTION_LINE_CREATED = typeof PRODUCTION_LINE_CREATED;

export const PRODUCTION_LINE_DELETED = "PRODUCTION_LINE_DELETED";
export type PRODUCTION_LINE_DELETED = typeof PRODUCTION_LINE_DELETED;
